name: build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build

    timeout-minutes: 10

    permissions:
      contents: write

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "walltaker-engine-build-cache"
      
      - name: install build deps
        run: choco install -y pkgconfiglite

      - name: install cargo deps
        run: cargo install cargo-wix

      - name: build release binary
        run: cargo wix --nocapture

      - name: publish artifact
        uses: softprops/action-gh-release@v1
        with:
          files: target/wix/walltaker-engine-*